/* Generate a no-allocation emergency ASCII face from bundled CC0 monogram. */
#define STB_TRUETYPE_IMPLEMENTATION
#include "../frogui/stb_truetype.h"
#include <stdio.h>
#include <stdlib.h>
int main(int argc,char **argv) {
    if(argc!=3)return 1;
    FILE *in=fopen(argv[1],"rb");if(!in)return 2;
    fseek(in,0,SEEK_END);long size=ftell(in);rewind(in);
    unsigned char *data=malloc(size);if(!data)return 3;
    if(fread(data,1,size,in)!=(size_t)size)return 4;fclose(in);
    stbtt_fontinfo info;
    if(!stbtt_InitFont(&info,data,0))return 5;
    float scale=stbtt_ScaleForPixelHeight(&info,16);
    int ascent;stbtt_GetFontVMetrics(&info,&ascent,NULL,NULL);
    FILE *out=fopen(argv[2],"wb");if(!out)return 6;
    fprintf(out,"/* Generated by tests/make_font_fallback.c from monogram (datagoblin, CC0 1.0). */\n#ifndef SWITCHFROG_FONT_FALLBACK_H\n#define SWITCHFROG_FONT_FALLBACK_H\nstatic const unsigned char fallback_ascii[95][16] = {\n");
    for(int ch=32;ch<127;ch++){
        int w,h,xoff,yoff;
        unsigned char rows[16]={0};
        unsigned char *bitmap=stbtt_GetCodepointBitmap(&info,0,scale,ch,&w,&h,&xoff,&yoff);
        for(int y=0;y<h;y++)for(int x=0;x<w;x++){
            int px=x+xoff,py=y+yoff+(int)(ascent*scale);
            if(px>=0&&px<8&&py>=0&&py<16&&bitmap[y*w+x]>=96)rows[py]|=1u<<px;
        }
        fprintf(out," {");for(int y=0;y<16;y++)fprintf(out,"%s0x%02x",y?",":"",rows[y]);
        fprintf(out,"}, /* ASCII %d */\n",ch);stbtt_FreeBitmap(bitmap,NULL);
    }
    fprintf(out,"};\n#endif\n");fclose(out);free(data);return 0;
}
